export default {
    THEME_CHANGE: 'THEME_CHANGE',

    //最新
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_REFRESH_FAILED: "POPULAR_REFRESH_FAILED",
    POPULAR_LOAD_MORE_FAILED: "POPULAR_LOAD_MORE_FAILED",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",

    //趋势
    TRENDING_REFRESH: "TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",

    //收藏
    FAVORITE_REFRESH: "FAVORITE_REFRESH",
    FAVORITE_REFRESH_SUCCESS: "FAVORITE_REFRESH_SUCCESS",
    FAVORITE_REFRESH_FAIL: "FAVORITE_REFRESH_FAIL",


}