export default {
    THEME_CHANGE: 'THEME_CHANGE',
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_REFRESH_FAILED: "POPULAR_REFRESH_FAILED",
    POPULAR_LOAD_MORE_FAILED: "POPULAR_LOAD_MORE_FAILED",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",
}